[package]
name = "mooncreditfi"
edition = "2026"   
# license = "MIT"         
# authors = ["Zakaria sisu (zakariasisu5@gmail.com)"]

[dependencies]

# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
